[env:nodemcuv2]
platform = espressif8266
board = nodemcuv2
framework = arduino
upload_speed = 921600
monitor_speed = 115200

; 文件系统配置 - 1MB SPIFFS
board_build.filesystem = spiffs
board_build.spiffs_size = 1048576
lib_ldf_mode = deep

; 依赖库
lib_deps =
    SPI
    ESP8266WiFi
    ESP8266WebServer
    adafruit/Adafruit SHT31 Library@^2.2.0
